services:
  - name: BR-service
    type: web
    buildCommand: npm install && npm run build # Ajusta esto según tu proyecto
    startCommand: npm start # Ajusta esto según tu proyecto
    env:
      - key: DATABASE_URL
        fromDatabase:
          name: byr
          property: postgres://luis:mFZoGtV2BJMP0fsAnZUWjUyWEcw3zvTU@dpg-ck67hcb6fquc73dhh9ag-a.oregon-postgres.render.com/byr
